#!/usr/bin/env bash
#
# Generates local-only development credentials.
#
# Nothing secret is committed to this repository. This script creates the .env file and
# the local credential directory that Docker Compose needs, using freshly generated
# random passwords. Both are gitignored.
#
# Safe to re-run: existing files are left alone so the database and the credential files
# cannot drift out of sync.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="${repo_root}/.env"
creds_dir="${repo_root}/local/mongo-credentials"

if [[ -f "${env_file}" ]]; then
  echo "==> ${env_file} already exists, leaving it alone"
else
  echo "==> generating ${env_file}"
  cat > "${env_file}" <<EOF
# Local development only. Generated by scripts/bootstrap-local.sh. Gitignored.
MONGO_ROOT_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
MONGO_APP_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)

# Get a free key at https://www.themoviedb.org/settings/api and paste it here.
TMDB_API_KEY=
EOF
fi

# shellcheck disable=SC1090
source "${env_file}"

mkdir -p "${creds_dir}"
if [[ -f "${creds_dir}/username" ]]; then
  echo "==> ${creds_dir} already populated, leaving it alone"
else
  echo "==> writing ${creds_dir}"
  # Matches the users seeded by docker/mongo-init.js. The application reads these two
  # files exactly as it reads the mounted Kubernetes Secret in-cluster.
  printf 'app_a' > "${creds_dir}/username"
  printf '%s' "${MONGO_APP_PASSWORD}" > "${creds_dir}/password"
  chmod 600 "${creds_dir}/username" "${creds_dir}/password"
fi

if [[ -z "${TMDB_API_KEY:-}" ]]; then
  echo
  echo "!! TMDB_API_KEY is empty in ${env_file}"
  echo "   The stack will start and /healthz will pass, but /search will return 502"
  echo "   until you add a key from https://www.themoviedb.org/settings/api"
fi

echo "==> local bootstrap complete"
